name: wheels-linux

on: [push, pull_request]

jobs:
  build_wheels_linux:
    name: Build wheels on linux
    runs-on: ubuntu-20.04 

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.7.0

      - name: Install pyomo pybind
        run: python -m pip install pybind11 pyomo

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Create install dir
        run: cmake -E make_directory ${{runner.workspace}}/installs/

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/installs/highs -DFAST_BUILD=ON

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build . --parallel 
          cmake --install .

      - name: Build wheels
        run: |
          export REPAIR_LIBRARY_PATH=${{runner.workspace}}/installs/highs/lib
          export LD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH
          export DYLD_LIBRARY_PATH=$REPAIR_LIBRARY_PATH
          cd  $GITHUB_WORKSPACE/src/interfaces/highspy
          python -m cibuildwheel --output-dir wheelhouse
        # ls $REPAIR_LIBRARY_PATH
        # to supply options, put them in 'env', like:

        env:
          CIBW_ENVIRONMENT: REPAIR_LIBRARY_PATH=${{runner.workspace}}/installs/highs/lib 

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl